version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-rs0
    command: --replSet rs0 --keyFile /etc/mongo-keyfile
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: kanban
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
